services:
  - docker
matrix:
  include:
    - language: python
      cache: pip
      python:
        - "3.6"
      before_install:
        - cd backend/gitdrnk
      install:
        - pip install --upgrade pip
        - pip install -r requirements.txt
      script:
        - echo $TRAVIS_BUILD_NUMBER

    - language: node_js
      cache: npm
      node_js:
        - "stable"
      before_install:
        - cd frontend/gitdrnk
      install:
        - npm install
      script:
        - npm test
        - npm run build
