apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitdrnkdeployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gitdrnk
    spec:
      containers:
        - name: gitdrnk
          image: sellnat77/gitdrnk:test3
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
