apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitdrnkdeployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gitdrnk
    spec:
      containers:
        - name: gitdrnk
          image: sellnat77/gitdrnk:v2
          env:
            - name: "MONGO_URI"
              value: "unknown"
            - name: "GUNICORN_WORKERS"
              value: 2
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
