kind: Service
apiVersion: v1
metadata:
  name: frontendservice
spec:
  selector:
    app: gitdrnk-react
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3001
      # Port to forward to inside the pod
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer
