apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: andresvidal/rpi3-mongodb3
          ports:
            - containerPort: 27017
